STARIONGROUP/COMET-SDK-Community-Edition

CDP4Common.Tests/Helpers/NestedElementTreeGeneratorTestFixtre.cs
CDP4Common/Helpers/NestedElementTreeGenerator.cs

The class CDP4Common.Helpers.NestedElementsTreeGenerator was fulfilled with a GetNestedParameters function, which returns all the NestedParameters for the Option as a flat List<NestedParameters>.

[Add] Getting a NestedParameters as a flat list function

---

CDP4Dal.NetCore.Tests/SessionTestFixture.cs
CDP4Dal.Tests/SessionTestFixture.cs
CDP4Dal/Session.cs

The Session.Open method has been refactored to set the `ActivePerson` property. If the person is not found in the JSON response an exception is thrown. Calling methods on session are not allowed when the `ActivePerson` has not been set.

GH55 - refacor Open method and ActivePerson property

---

CDP4JsonSerializer.Tests/Helper/SerializerHelperTestFixture.cs
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4JsonSerializer/Helper/SerializerHelper.cs

- Fixed bug in JSON to ValueArray<T> deserialization code
- Created extra unit tests to check if serialization/deserialization is done correct
- Some boyscouting

Fixed bug in JSON to ValueArray<T> deserialization code

---

CDP4ServicesDal.NetCore.Tests/PostOperationTestFixture.cs
CDP4ServicesDal.Tests/PostOperationTestFixture.cs
CDP4WspDal.NetCore.Tests/PostOperationTestFixture.cs
CDP4WspDal.Tests/PostOperationTestFixture.cs

PostOperation tests are extended by adding a check for serialization. Closes #57

[Update] PostOperation tests by adding a check for serialization

---

CDP4Dal.NetCore.Tests/Permission/PermissionServiceTestFixture.cs
CDP4Dal.Tests/Permission/PermissionServiceTestFixture.cs
CDP4Dal/Permission/PermissionService.cs

- Bugfix
- Boyscouting null checks and direct output vars
- Refactoring of PermissionService.CanWriteIfParticipantOwned method. CommonFileStore implementation did not work OK (checked at TopContainer instead of Container property) and it is also moved to the top of the method.
All other cases now return False when needed.
- Boyscouting (null checks and out vars)
- Adding unit tests for Requirement and for a direct child of EngineeringModel (in this case CommonFileStore)

Bugfix MODIFY_IF_OWNED fixes GH80

---

CDP4Common.NetCore.Tests/Types/OrderedItemListTestFixture.cs
CDP4Common.Tests/Types/OrderedItemListTestFixture.cs
CDP4Common/Types/OrderedItemList.cs

Fix type comparison in OrderedItemList

---

CDP4Dal.NetCore.Tests/Permission/PermissionServiceTestFixture.cs
CDP4Dal.Tests/Permission/PermissionServiceTestFixture.cs
CDP4Dal/CDP4Dal.csproj
CDP4Dal/Permission/PermissionService.cs
CDP4ServicesDal.NetCore.Tests/CdpServicesDalTestFixture.cs
CDP4ServicesDal.NetCore.Tests/OperationModifierTestFixture.cs
CDP4ServicesDal.NetCore.Tests/ValueSetOperationCreatorTestFixture.cs
CDP4ServicesDal.Tests/CdpServicesDalTestFixture.cs
CDP4ServicesDal.Tests/CopyOperationHandlerTestFixture.cs
CDP4ServicesDal.Tests/OperationModifierTestFixture.cs
CDP4ServicesDal.Tests/ValueSetOperationCreatorTestFixture.cs
CDP4WspDal.NetCore.Tests/OperationModifierTestFixture.cs
CDP4WspDal.NetCore.Tests/SessionTestFixture.cs
CDP4WspDal.NetCore.Tests/ValueSetOperationCreatorTestFixture.cs
CDP4WspDal.NetCore.Tests/WSPDalTestFixture.cs
CDP4WspDal.Tests/CopyOperationHandlerTestFixture.cs
CDP4WspDal.Tests/OperationModifierTestFixture.cs
CDP4WspDal.Tests/SessionTestFixture.cs
CDP4WspDal.Tests/ValueSetOperationCreatorTestFixture.cs
CDP4WspDal.Tests/WSPDalTestFixture.cs

[Fix] bugs of PermissionService and its test

---

CDP4Common.NetCore.Tests/Poco/FileRevisionTestFixture.cs
CDP4Common/CDP4Common.csproj
CDP4Common/Poco/FileRevision.cs

Fix null reference in Folder.GetDerivedPath method

Fix Folder.GetDerivedPath()

---

CDP4Common.Tests/Poco/FileRevisionTestFixture.cs
CDP4Common/CDP4Common.csproj
CDP4Common/Poco/FileRevision.cs

A FileType could have an empty extension.
In that case the extension and the including separator (dot) should not be added to the path property.

Do not add empty extensions to the calculated path

---

CDP4Common.NetCore.Tests/Helpers/ValueSetConverterTestFixture.cs
CDP4Common.NetCore.Tests/Poco/OptionTestFixture.cs
CDP4Common.Tests/Helpers/ValueSetConverterTestFixture.cs
CDP4Common.Tests/Poco/OptionTestFixture.cs
CDP4Common/Helpers/ValueSetConverter.cs
CDP4Common/Poco/Option.cs

ValueSetConverter.TryParseDouble tries to converts a string to a double using 10-25 rules.

Fixes #136 Added ValueSetConverter.TryParseDouble

---

CDP4Common.NetCore.Tests/Poco/NestedElementTestFixture.cs
CDP4Common.Tests/Poco/NestedElementTestFixture.cs
CDP4Common/Extensions/CategorizableThingExtensions.cs
CDP4Common/Poco/Category.cs
CDP4Common/Poco/ElementDefinition.cs
CDP4Common/Poco/ElementUsage.cs
CDP4Common/Poco/NestedElement.cs

Extra overload that doesn't use the Cache and is therefore faster.

Fixes #138; Extra IsMemberOfCategory overload that does not use the Cache

---

CDP4Dal.NetCore.Tests/DAL/DalTestFixture.cs
CDP4Dal.Tests/DAL/DalTestFixture.cs
CDP4Dal/DAL/Dal.cs
CDP4ServicesDal/CdpServicesDal.cs
CDP4WspDal/WSPDal.cs
appveyor.yml

The UriBuilder usage refactored not to lose folders in server uri's. connected to https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues/571

[Fix] Uri contexts are no longer ignored when logging in. Fixes IME#571

---

CDP4Common/Polyfills/TypePolyfills.cs
CDP4Dal/AvailableDals.cs
CDP4Dal/Composition/DalExportAttribute.cs
CDP4JsonFileDal/JsonFileDal.cs
CDP4JsonSerializer/Helper/Utils.cs
CDP4ServicesDal/CdpServicesDal.cs
CDP4WspDal/WSPDal.cs

The net48 target was added to the csproj file, but the compiler conditional statements had not yet been updated, see sample below
```
#if NET45 || NET451 || NET452 || NET46 || NET461 || NET462 || NET47 || NET471 || NET472 || NET48
some-code-goes-here
#endif
```

[Add] NET48 to compiler conditional statement

---

CDP4Dal/DAL/Dal.cs
CDP4JsonFileDal/JsonFileDal.cs

To support functionality of the Syncer, JsonFileDal must provide possibility to read SRDls and DomainsOfExpertise. Currently only Iterations are supported.

Expand support of reading SRDLs and DomainOfExpertise from JSONFileDal

---

CDP4Dal.Tests/SessionTestFixture.cs
CDP4Dal/Session.cs

#167 Investigate changing of the ISession.Read(Iteration iteration, DomainOfExpertise domain) method signature

---

CDP4Dal.NetCore.Tests/CDP4Dal.NetCore.Tests.csproj
CDP4Dal.NetCore.Tests/MessageBusTestFixture.cs
CDP4Dal.Tests/CDP4Dal.Tests.csproj
CDP4Dal.Tests/MessageBusTestFixture.cs
CDP4Dal/CDPMessageBus.cs

Removed unnecessary extra creation of IObservalues in CDPMessageBus to reduce memory consumption and added specific unit tests.

Reduce CDPMessageBus memory consumption and added dotMemory unit tests

---

CDP4Common/CDP4Common.csproj
CDP4Dal/CDP4Dal.csproj
CDP4Dal/CDPMessageBus.cs
CDP4Dal/ISession.cs
CDP4Dal/Session.cs
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4Rules/CDP4Rules.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4WspDal/CDP4WspDal.csproj
appveyor.yml

#193 Support for open read silently

---

CDP4Common/CDP4Common.csproj
CDP4Common/Helpers/ValueArrayUtils.cs
CDP4JsonSerializer.NetCore.Tests/JsonSerializerTestFixture.cs
CDP4JsonSerializer.Tests/JsonSerializerTestFixture.cs
CDP4JsonSerializer/Helper/SerializerHelper.cs
CDP4ServicesDal.NetCore.Tests/CdpServicesDalTestFixture.cs
CDP4ServicesDal.Tests/CdpServicesDalTestFixture.cs
appveyor.yml
comet_sdk_test_netf.bat

Fixes a bug on deserializing ValueSets that contain specific escape characters that aren't used as escape characters.

[Fix] Deserialize ValueSets ;Fixes #205 

---

CDP4RequirementsVerification.Tests/Verifiers/RequirementsContainerVerifierTestFixture.cs
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4RequirementsVerification/Verifiers/OrExpressionVerifier.cs
CDP4RequirementsVerification/Verifiers/RequirementsContainerVerifier.cs

Requirements Verification on RequirementsGroups isn't executed propery.

[FIX] Requirements Verification on RequirementsGroups; fixes #214

---

CDP4Common.NetCore.Tests/Extensions/BooleanExpressionExtensionsTestFixture.cs
CDP4Common.NetCore.Tests/Extensions/ParametricConstraintExtensionsTestFixture.cs
CDP4Common.Tests/Extensions/BooleanExpressionExtensionsTestFixture.cs
CDP4Common.Tests/Extensions/ParametricConstraintExtensionsTestFixture.cs
CDP4Common/CDP4Common.csproj
CDP4Common/Extensions/BooleanExpressionExtensions.cs
CDP4Common/Extensions/ParametricConstraintExtensions.cs
CDP4Common/Poco/AndExpression.cs
CDP4Common/Poco/BooleanExpression.cs
CDP4Common/Poco/ExclusiveOrExpression.cs
CDP4Common/Poco/NotExpression.cs
CDP4Common/Poco/OrExpression.cs
CDP4Common/Poco/RelationalExpression.cs

Move BooleanExpression => Expression string logic from IME to SDK

Move BooleanExpression => Expression string logic from IME to SDK; fixes #220

---

CDP4Dal/Exceptions/TransactionException.cs
CDP4Dal/Operations/ThingTransaction.cs

Updated the ThingTransactionException namespace to Dal. This is a braking change that warrants a major release

[Update] ThingTransactionException namespace; fixes #154

---

CDP4Common.NetCore.Tests/Helpers/ValueArrayUtilsTestFixture.cs
CDP4Common.Tests/Extensions/ElementBaseExtensionsTestFixture.cs
CDP4Common.Tests/Helpers/ValueArrayUtilsTestFixture.cs
CDP4Common.Tests/Poco/IterationTestFixture.cs
CDP4Common/Extensions/ElementBaseExtensions.cs
CDP4Common/Extensions/ParameterOrOverrideBaseExtensions.cs
CDP4Common/Helpers/ValueArrayUtils.cs
CDP4Common/Poco/ElementBase.cs
CDP4Common/Poco/Iteration.cs
CDP4Common/Poco/ParameterSubscription.cs
CDP4Common/Poco/ParameterSubscriptionValueSet.cs

Copy extensions and helper methods from web app to SDK. Once new SDK release is made, comet web app should use these methods instead

[Implement] extension methods from webapp; fixes #251

---

CDP4Reporting.Tests/DataCollection/OptionDependentDataCollectorTestFixture.cs
CDP4Reporting/CDP4Reporting.csproj
CDP4Reporting/DataCollection/OptionDependentDataCollector.cs

SelectedOption is not set by manual option selection for reports

[Fix] SelectedOption is not set by manual option selection for reports; fixes #260

---

CDP4Common.NetCore.Tests/Helpers/NestedElementTreeGeneratorTestFixture.cs
CDP4Common/Helpers/NestedElementTreeGenerator.cs
RemoveObjAndBin.ps1

- Add null reference check before trying to access the `formula` or `actualvalue` property; fixes #243 
- [Fix] incorrect setting of NestedParameter.AssociatedParameter when is ParameterOverride; fixes #241

[Refactor] NestedElementTreeGenerator

---

CDP4Dal.NetCore.Tests/Permission/PermissionServiceTestFixture.cs
CDP4Dal.Tests/Permission/PermissionServiceTestFixture.cs
CDP4Dal/CDP4Dal.csproj
CDP4Dal/Permission/IPermissionService.cs
CDP4Dal/Permission/PermissionService.cs

[ADD] CanCreateOverride functionality to check for specific Create permissions

[ADD] CanCreateOverride functionality to check for specific Create permissions

---

CDP4Common/CDP4Common.csproj
CDP4Dal/CDP4Dal.csproj
CDP4Dal/CDPMessageBus.cs
CDP4Dal/ICDPMessageBus.cs
CDP4Dal/ISession.cs
CDP4Dal/Session.cs
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4MessagePackSerializer/CDP4MessagePackSerializer.csproj
CDP4Reporting/CDP4Reporting.csproj
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4Rules/CDP4Rules.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4Web/CDP4Web.csproj
CDP4WspDal/CDP4WspDal.csproj

[ADD] ISession now implements CDPMessageBus property
[FIX] ICDPMessageBus inherits IDisposable

[FIX] ICDPMessageBus inherits IDisposable and accessible from ISession interface

---

CDP4Common.NetCore.Tests/Extensions/EnumerationParameterTypeExtensionsTestFixture.cs
CDP4Common.Tests/Extensions/EnumerationParameterTypeExtensionsTestFixture.cs
CDP4Common/Extensions/EnumerationParameterTypeExtensions.cs

[ADD] ResolveName extension Method for EnumerationParameterType

[ADD] ResolveName extension Method for EnumerationParameterType; fixes #310

---

CDP4Common.NetCore.Tests/Validation/DtoValueValidatorTestFixture.cs
CDP4Common.Tests/Validation/DtoValueValidatorTestFixture.cs
CDP4Common/Extensions/ParameterTypeExtensions.cs
CDP4Common/Validation/DtoValueValidator.cs

Fix #317: Guid? passed instead of Scale and ParameterBase validation

---

CDP4Common.NetCore.Tests/Validation/DtoValueValidatorTestFixture.cs
CDP4Common.Tests/Validation/DtoValueValidatorTestFixture.cs
CDP4Common/Validation/DtoValueValidator.cs

While implementing https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues/335, realized that validation should be done at ClasslessDTO level instead of on ParameterValueSet

ClasslessDTO Validation

---

CDP4Common.NetCore.Tests/Validation/DtoValueValidatorTestFixture.cs
CDP4Common.Tests/Validation/DtoValueValidatorTestFixture.cs
CDP4Common/CDP4Common.csproj
CDP4Common/Validation/ObjectValueValidator.cs
CDP4Dal/CDP4Dal.csproj
CDP4DalCommon/CDP4DalCommon.csproj
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4MessagePackSerializer/CDP4MessagePackSerializer.csproj
CDP4Reporting/CDP4Reporting.csproj
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4Rules/CDP4Rules.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4ServicesMessaging/CDP4ServicesMessaging.csproj
CDP4Web/CDP4Web.csproj
CDP4WspDal/CDP4WspDal.csproj

TimeOfDayParameterType conversion doesn't work as expected; fixes #328

TimeOfDayParameterType conversion doesn't work as expected; fixes #328

---

CDP4Common.NetCore.Tests/Validation/DtoValueValidatorTestFixture.cs
CDP4Common.Tests/Validation/DtoValueValidatorTestFixture.cs
CDP4Common/Validation/ObjectValueValidator.cs
CDP4Dal/CDP4Dal.csproj

Time of day parameter type converts to a wrong value

Time of day parameter type converts to a wrong value; fixes #328

---

CDP4Dal/DAL/Credentials.cs
CDP4ServicesDal.NetCore.Tests/CdpServicesDalTestFixture.cs
CDP4ServicesDal.Tests/CdpServicesDalTestFixture.cs
CDP4ServicesDal/CdpServicesDal.cs

added the capability to enable full trust of all SSL certs, including self-signed certs

[Add] the ability to enable trusting self signed certificates; fixes 338

---

CDP4Common/CDP4Common.csproj
CDP4Common/Validation/DtoValueValidator.cs
CDP4Dal/CDP4Dal.csproj
CDP4DalCommon/CDP4DalCommon.csproj
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4MessagePackSerializer/CDP4MessagePackSerializer.csproj
CDP4Reporting/CDP4Reporting.csproj
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4Rules/CDP4Rules.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4ServicesMessaging/CDP4ServicesMessaging.csproj
CDP4Web/CDP4Web.csproj
CDP4WspDal/CDP4WspDal.csproj

[REFACTOR] ParameterOrOverrideBase instead of Parameter for DtoValueValidator.ValidateAndCleanup

[REFACTOR] ParameterOrOverrideBase instead of Parameter for DtoValueValidator.ValidateAndCleanup

---

CDP4Common/CDP4Common.csproj
CDP4Dal.NetCore.Tests/Permission/PermissionServiceTestFixture.cs
CDP4Dal.Tests/Permission/PermissionServiceTestFixture.cs
CDP4Dal/CDP4Dal.csproj
CDP4Dal/Permission/PermissionService.cs
CDP4DalCommon/CDP4DalCommon.csproj
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4MessagePackSerializer/CDP4MessagePackSerializer.csproj
CDP4Reporting/CDP4Reporting.csproj
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4Rules/CDP4Rules.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4ServicesMessaging/CDP4ServicesMessaging.csproj
CDP4Web/CDP4Web.csproj
CDP4WspDal/CDP4WspDal.csproj

[FIX] PermissionService Owned Things directly contained in EngineeringModel and their full containment tree

[WIP][FIX] PermissionService Owned Things directly contained in EngineeringModel and their full containment tree
