STARIONGROUP/COMET-SDK-Community-Edition

appveyor.yml

Fix branches config

---

CDP4Dal/Permission/PermissionService.cs

[Delete] unreachable code. Closes #51.

---

CDP4Common/AutoGenHelpers/DefaultPermissionProvider.cs
CDP4Common/Poco/ParticipantRole.cs
CDP4Common/Poco/PersonRole.cs

Update DefaultPermissionProvider to expose additional data and ParticipantRole and PersonRole to utilize it. Details see #11 
Closes #11

[Update] DefaultPermissionProvider to expose additional data

---

CDP4Common/Comparers/DtoThingIidComparer.cs

A DTO Thing comparer is added.

[Add] DTO Thing comparer for equality comparison for collections

---

CDP4Common/CDP4Common.csproj
CDP4Common/Poco/RelationalExpression.cs
CDP4Common/Poco/RelationalOperatorKindMethods.cs

A better (scientific) representation of RelationalOperators is needed in the IME's RequirementsBrowser. 
An extension method is created for that reason, so it can be used in a RelationalExpression and in other places where the same presentation is required.

Userfriendly string for relationaloperators

---

CDP4Dal.Tests/SessionTestFixture.cs
CDP4Dal/ISession.cs
CDP4Dal/Session.cs
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4ServicesDal/CdpServicesDal.cs

Cancellation support for file download (ReadFilemethod in Session and DAL).
Support for multipart HTML response messages.

Fixes #109 Implements multipart message fix and cancellation of file download.

---

CDP4Common/Poco/Option.cs

Bugfix null check in Option.IsDefault.

Fixes #119 Null check Option.IsDefault

---

README.md
appveyor.yml

add sonarcloud metrics to README.md

add sonarcloud metrics to README.md

---

CDP4Common.NetCore.Tests/CDP4Common.NetCore.Tests.csproj
CDP4Common.Tests/CDP4Common.Tests.csproj
CDP4Common/CDP4Common.csproj
CDP4Dal.NetCore.Tests/CDP4Dal.NetCore.Tests.csproj
CDP4Dal.Tests/CDP4Dal.Tests.csproj
CDP4Dal/CDP4Dal.csproj
CDP4JsonFileDal.NetCore.Tests/CDP4JsonFileDal.NetCore.Tests.csproj
CDP4JsonFileDal.NetCore.Tests/JsonFileDalTestFixture.cs
CDP4JsonFileDal.Tests/CDP4JsonFileDal.Tests.csproj
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4JsonSerializer.NetCore.Tests/CDP4JsonSerializer.NetCore.Tests.csproj
CDP4JsonSerializer.Tests/CDP4JsonSerializer.Tests.csproj
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4RequirementsVerification.Tests/CDP4RequirementsVerification.Tests.csproj
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4Rules.NetCore.Tests/CDP4Rules.NetCore.Tests.csproj
CDP4Rules/CDP4Rules.csproj
CDP4ServicesDal.NetCore.Tests/CDP4ServicesDal.NetCore.Tests.csproj
CDP4ServicesDal.Tests/CDP4ServicesDal.Tests.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4WspDal.NetCore.Tests/CDP4WspDal.NetCore.Tests.csproj
CDP4WspDal.Tests/CDP4WspDal.Tests.csproj
CDP4WspDal/CDP4WspDal.csproj

Preparation of SDK for version 6.2 release, including the following csproj files updates:
[Add] targetframeworks net48 and netstandard2.1
[Add] Microsoft.NETFramework.ReferenceAssemblies package
[Update] NUnit3TestAdapter, Microsoft.NET.Test.Sdk and Moq
[Update] version numbers to 6.2.0

Preparation of SDK for version 6.2 release

---

CDP4Common.Tests/Helpers/NestedElementTreeGeneratorTestFixture.cs
CDP4Common.Tests/Poco/OptionTestFixture.cs
CDP4Common/Poco/Category.cs
CDP4Common/Poco/NestedParameter.cs
CDP4Common/Poco/Option.cs
CDP4Common/Poco/ParameterBase.cs

Helper methods for writing parameter values from a report preview to the model

Fixes #133 helpermethods set valueset by path

---

CDP4Dal.NetCore.Tests/DAL/DalTestFixture.cs
CDP4Dal.Tests/DAL/DalTestFixture.cs
CDP4Dal/CDP4Dal.csproj
CDP4Dal/DAL/Dal.cs
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4ServicesDal/CdpServicesDal.cs
CDP4WspDal/CDP4WspDal.csproj
CDP4WspDal/WSPDal.cs
appveyor.yml

Bumped version numbers to 6.2.2

---

CDP4Dal.Tests/SessionTestFixture.cs
CDP4Dal/CDP4Dal.csproj
CDP4Dal/ISession.cs
CDP4Dal/Session.cs
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4WspDal/CDP4WspDal.csproj

Bugfix and refactoring DomainOfExpertise from Session/ISession

Fixes #151 DomainOfExpertise from session

---

CDP4Dal.NetCore.Tests/Events/BeforeWriteEventArgsTestFixture.cs
CDP4Dal.NetCore.Tests/SessionTestFixture.cs
CDP4Dal.Tests/Events/BeforeWriteEventArgsTestFixture.cs
CDP4Dal.Tests/SessionTestFixture.cs
CDP4Dal/CDP4Dal.csproj
CDP4Dal/Events/BeforeWriteEventArgs.cs
CDP4Dal/ISession.cs
CDP4Dal/Session.cs
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4WspDal/CDP4WspDal.csproj

Added ISession.BeforeWrite event

Fixes #158 Added ISession.BeforeWrite event

---

CDP4Dal/Session.cs
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4ServicesDal/CdpServicesDal.cs
CDP4ServicesDal/Headers.cs

Bumped version of the Dal extension version support

CDP4 Extension 1.2.0 bump for Dal

---

CDP4Common/AutoGenDto/SampledFunctionParameterType.cs
CDP4Common/AutoGenMetaInfo/SampledFunctionParameterTypeMetaInfo.cs
CDP4Common/AutoGenPoco/SampledFunctionParameterType.cs
CDP4Common/CDP4Common.csproj
CDP4Common/Poco/NestedParameter.cs
CDP4Common/Poco/ParameterSubscriptionValueSet.cs
CDP4Common/Poco/ParameterValueSetBase.cs
CDP4Common/Poco/SampledFunctionParameterType.cs
CDP4Dal.NetCore.Tests/SessionTestFixture.cs
CDP4Dal.Tests/SessionTestFixture.cs
CDP4Dal/CDP4Dal.csproj
CDP4Dal/DAL/Dal.cs
CDP4Dal/Session.cs
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4JsonSerializer/AutoGenDtoDeserializer/SampledFunctionParameterTypeResolver.cs
CDP4JsonSerializer/AutoGenDtoSerializer/SampledFunctionParameterTypeSerializer.cs
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4Rules/CDP4Rules.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4WspDal/CDP4WspDal.csproj

UML had missing ValueArray profile and isOrdered setting on SampledFunctionParameterType

Fix SampledFunctionParameterType value array

---

CDP4Common.NetCore.Tests/Poco/NestedElementTestFixture.cs
CDP4Common.Tests/Poco/NestedElementTestFixture.cs
CDP4Common/CDP4Common.csproj
CDP4Common/Poco/NestedElement.cs

Fix NestedElement.GetChildren method.

[Fix] NestedElement.GetChildren

---

CDP4Common/CDP4Common.csproj
CDP4Common/Exceptions/ThingNotFoundException.cs
CDP4JsonFileDal/JsonFileDalUtils.cs

[Add] ThingNotFoundException; refactor JsonFileDalUtils to check null on SiteDirectoryDto and throw ThingNotFoundException; fixes https://sonarcloud.io/project/issues?id=RHEAGROUP_CDP4-SDK-Community-Edition&issues=AXMUfUzN4PCXjoHPXXnY&open=AXMUfUzN4PCXjoHPXXnY

[SonarQube] improvement

---

CDP4Common.NetCore.Tests/CDP4Common.NetCore.Tests.csproj
CDP4Common.Tests/CDP4Common.Tests.csproj
CDP4Common/CDP4Common.csproj
CDP4Dal.NetCore.Tests/CDP4Dal.NetCore.Tests.csproj
CDP4Dal.Tests/CDP4Dal.Tests.csproj
CDP4Dal/CDP4Dal.csproj
CDP4JsonFileDal.NetCore.Tests/CDP4JsonFileDal.NetCore.Tests.csproj
CDP4JsonFileDal.Tests/CDP4JsonFileDal.Tests.csproj
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4JsonSerializer.NetCore.Tests/CDP4JsonSerializer.NetCore.Tests.csproj
CDP4JsonSerializer.Tests/CDP4JsonSerializer.Tests.csproj
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4JsonSerializer/Cdp4JsonSerializer.cs
CDP4JsonSerializer/JsonConverter/ClassKindConverter.cs
CDP4RequirementsVerification.Tests/CDP4RequirementsVerification.Tests.csproj
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4Rules.NetCore.Tests/CDP4Rules.NetCore.Tests.csproj
CDP4Rules/CDP4Rules.csproj
CDP4ServicesDal.NetCore.Tests/CDP4ServicesDal.NetCore.Tests.csproj
CDP4ServicesDal.Tests/CDP4ServicesDal.Tests.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4ServicesDal/CdpServicesDal.cs
CDP4WspDal.NetCore.Tests/CDP4WspDal.NetCore.Tests.csproj
CDP4WspDal.Tests/CDP4WspDal.Tests.csproj
CDP4WspDal/CDP4WspDal.csproj
appveyor.yml

Serialize ClassKind enum to string representation instead of int value.
Also COMETized CDPServiceDal description

fixes #184 Serialize ClassKind enum to string representation instead of int value

---

CDP4Common/Dto/Attachment.cs
CDP4Common/Dto/FileRevision.cs
CDP4Common/Dto/ILocalFile.cs
CDP4Common/Poco/Attachment.cs
CDP4Dal/DAL/Dal.cs

Fixed interface for attachments and DAL handling of file verification

---

CDP4Common.NetCore.Tests/Poco/ParticipantRoleTestFixture.cs
CDP4Common.Tests/Poco/ParticipantRoleTestFixture.cs
CDP4Dal/Session.cs

[Fix] ParticipantRole count
[Fix] Session Cancellation

Participant Role test and session fix

---

appveyor.yml
comet_sdk_test_netf.bat

CI Build net472 instead of net48

Build net 472 instead of net48

---

CDP4Dal/Exceptions/DalVersionException.cs
CDP4JsonFileDal.NetCore.Tests/JsonFileDalTestFixture.cs
CDP4JsonFileDal.NetCore.Tests/files/migration.json
CDP4JsonFileDal.Tests/JsonFileDalTestFixture.cs
CDP4JsonFileDal/JsonFileDal.cs

Implement version check in JsonFileDal CTOR

[ADD] Implement version check in JsonFileDal CTOR

---

CDP4Common/CDP4Common.csproj
CDP4Dal/CDP4Dal.csproj
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4JsonSerializer.NetCore.Tests/JsonSerializerTestFixture.cs
CDP4JsonSerializer.Tests/JsonSerializerTestFixture.cs
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4JsonSerializer/JsonConverter/ThingConverterExtensions.cs
CDP4JsonSerializer/JsonConverter/ThingSerializer.cs
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4Rules/CDP4Rules.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4WspDal/CDP4WspDal.csproj

[ADD] Category.PermissibleClasses version check to ThingSerializer

[ADD] Category.PermissibleClasses version check to ThingSerializer; fixes #216

---

CDP4RequirementsVerification.Tests/Builders/ParameterBuilder.cs
CDP4RequirementsVerification.Tests/Verifiers/ParametricConstraintVerifierTestFixture.cs
CDP4RequirementsVerification.Tests/Verifiers/RelationalExpressionVerifierTestFixture.cs
CDP4RequirementsVerification.Tests/Verifiers/RequirementsContainerVerifierTestFixture.cs
CDP4RequirementsVerification.Tests/Verifiers/RequirementsVerifierTestFixture.cs
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4RequirementsVerification/Verifiers/AndExpressionVerifier.cs
CDP4RequirementsVerification/Verifiers/BaseVerifier.cs
CDP4RequirementsVerification/Verifiers/BooleanExpressionVerifier.cs
CDP4RequirementsVerification/Verifiers/ExclusiveOrExpressionVerifier.cs
CDP4RequirementsVerification/Verifiers/IRequirementVerificationConfiguration.cs
CDP4RequirementsVerification/Verifiers/NotExpressionVerifier.cs
CDP4RequirementsVerification/Verifiers/OrExpressionVerifier.cs
CDP4RequirementsVerification/Verifiers/ParametricConstraintVerifier.cs
CDP4RequirementsVerification/Verifiers/RelationalExpressionVerifier.cs
CDP4RequirementsVerification/Verifiers/RequirementVerificationConfiguration.cs
CDP4RequirementsVerification/Verifiers/RequirementVerifier.cs
CDP4RequirementsVerification/Verifiers/RequirementsContainerVerifier.cs
CDP4RequirementsVerification/Verifiers/VerifiedRequirementStateOfComplianceList.cs

Add Option support in Requirements Verification; fixes #223

Add Option support in Requirements Verification; fixes #223

---

CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4RequirementsVerification/Calculations/RequirementStateOfComplianceCalculator.cs
CDP4RequirementsVerification/Verifiers/RequirementVerificationConfiguration.cs

Fix Requirement verification regarding Option dependent ElementUsages

Requirements verification option dependency on elementusage level; Fixes #230

---

CDP4ServicesDal.NetCore.Tests/CdpServicesDalTestFixture.cs
CDP4ServicesDal/CdpServicesDal.cs

[Add] injected HttpClient on the Open method

---

CDP4Common/AutoGenHelpers/IterationContainmentClassType.cs
CDP4Common/CDP4Common.csproj

Add iteration containment class type

 Implement possible relationship ClassKind list; fixes #237

---

CDP4Dal/CDP4Dal.csproj
CDP4Dal/Session.cs

[FIX] Session.CanCancel cancels tasks

[FIX] Session.CanCancel cancels tasks

---

CDP4Common.NetCore.Tests/Helpers/PocoThingFactoryTestFixture.cs
CDP4Common.NetCore.Tests/Types/OrderedItemListTestFixture.cs
CDP4Common.Tests/Helpers/PocoThingFactoryTestFixture.cs
CDP4Common.Tests/Types/OrderedItemListTestFixture.cs
CDP4Common/CDP4Common.csproj
CDP4Common/Exceptions/Cdp4ModelValidationException.cs
CDP4Common/Exceptions/IncompleteModelException.cs
CDP4Common/Exceptions/ModelErrorException.cs
CDP4Common/Helpers/PocoThingFactory.cs
CDP4Common/Types/OrderedItemList.cs
CDP4Dal/CDP4Dal.csproj
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4Rules/CDP4Rules.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4WspDal/CDP4WspDal.csproj

[FIX] Error when OrderedItemList loading fails, which results in an Iteration that cannot be loaded in IME

[FIX] Error when OrderedItemList loading fails

---

CDP4Common/CDP4Common.csproj
CDP4Dal/CDP4Dal.csproj
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4Reporting.Tests/CDP4Reporting.Tests.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
pre-release.bat

[UPGRADE] System.Reactive 5.0 after undo Microsoft Abstractions

[UPGRADE] System.Reactive 5.0 after undo Microsoft Abstractions

---

CDP4Common.NetCore.Tests/MetaInfo/MetadataProviderTestFixture.cs
CDP4Common.Tests/MetaInfo/MetadataProviderTestFixture.cs
CDP4Common/AutoGenMetaInfo/MetaDataProvider.cs
CDP4Common/CDP4Common.csproj
CDP4Common/MetaInfo/IMetaDataProvider.cs
CDP4Common/Poco/Thing.cs
CDP4Dal/CDP4Dal.csproj
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4MessagePackSerializer/CDP4MessagePackSerializer.csproj
CDP4Reporting/CDP4Reporting.csproj
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4Rules/CDP4Rules.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4WspDal/CDP4WspDal.csproj

[ADD] Query supported model versions; fixes #227

[ADD] Query supported model versions; fixes #227

---

.github/workflows/CodeQuality.yml

update gh action to rebuild solution when performing dotnet pack

[Update] GH action to fix that the dotnet pack fails

---

CDP4-SDK.sln.DotSettings
CDP4Common.NetCore.Tests/Validation/ValidationServiceTestFixture.cs
CDP4Common.Tests/Validation/ValidationServiceTestFixture.cs
CDP4Common/Validation/IValidationService.cs
CDP4Common/Validation/ValidationService.cs

Fixes #293 #294 
- ValidationService implemented on CDP4Common
- EmailAddress validation is more RFC 5321 compliant than previously

Fix #293 #294: Validation service implemented on CDP4Common and RFC5321

---

CDP4Common/CDP4Common.csproj
CDP4Dal.NetCore.Tests/DAL/DalTestFixture.cs
CDP4Dal.NetCore.Tests/SessionTestFixture.cs
CDP4Dal.Tests/DAL/DalTestFixture.cs
CDP4Dal.Tests/SessionTestFixture.cs
CDP4Dal/CDP4Dal.csproj
CDP4Dal/DAL/Dal.cs
CDP4Dal/DAL/IDal.cs
CDP4Dal/Session.cs
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4JsonFileDal/JsonFileDal.cs
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4MessagePackSerializer/CDP4MessagePackSerializer.csproj
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4Rules/CDP4Rules.csproj
CDP4ServicesDal.NetCore.Tests/CdpServicesDalTestFixture.cs
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4ServicesDal/CdpServicesDal.cs
CDP4Web/CDP4Web.csproj
CDP4WspDal/CDP4WspDal.csproj
CDP4WspDal/WSPDal.cs

@antoineatrhea still needs some work

[Add] capability to read EngineeringModel instances using the CDP4ServicesDal and ISession; fixes #303

---

CDP4Common.NetCore.Tests/Helpers/NestedElementTreeGeneratorTestFixture.cs
CDP4Common.Tests/Helpers/NestedElementTreeGeneratorTestFixture.cs
CDP4Common/Helpers/NestedElementTreeGenerator.cs

[Add] exception handling on NestedElementTreeGenerator for NestedParameter creation

[Add] exception handling on NestedElementTreeGenerator; fixes #308

---

.github/workflows/CodeQuality.yml
.github/workflows/codeql-analysis.yml
dependabot.yml

Add dependabot file to automate notification of nuget version updates

[Add] dependabot.dependabot.yml file

---

CDP4Common/CDP4Common.csproj
CDP4Common/Extensions/IRuleVerificationExtensions.cs
CDP4Common/Poco/BinaryRelationshipRule.cs
CDP4Common/Poco/DecompositionRule.cs
CDP4Common/Poco/MultiRelationshipRule.cs
CDP4Common/Poco/ParameterizedCategoryRule.cs
CDP4Dal/CDP4Dal.csproj
CDP4DalCommon/CDP4DalCommon.csproj
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4MessagePackSerializer/CDP4MessagePackSerializer.csproj
CDP4Reporting/CDP4Reporting.csproj
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4Rules/CDP4Rules.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4ServicesMessaging/CDP4ServicesMessaging.csproj
CDP4Web/CDP4Web.csproj
CDP4WspDal/CDP4WspDal.csproj

[REFACTOR] Rule Verification more human readable; fixes #343

[REFACTOR] gh343-Rule Verification more human readable

---

CDP4Common.NetCore.Tests/Validation/DtoValueValidatorTestFixture.cs
CDP4Common.Tests/Validation/DtoValueValidatorTestFixture.cs
CDP4Common/CDP4Common.csproj
CDP4Common/Validation/DtoValueValidator.cs
CDP4Dal/CDP4Dal.csproj
CDP4Dal/Session.cs
CDP4DalCommon/CDP4DalCommon.csproj
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4MessagePackSerializer/CDP4MessagePackSerializer.csproj
CDP4Reporting/CDP4Reporting.csproj
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4Rules/CDP4Rules.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4ServicesMessaging/CDP4ServicesMessaging.csproj
CDP4Web/CDP4Web.csproj
CDP4WspDal/CDP4WspDal.csproj

[FIX] DtoValueValidator on unwanted validation of Formula properties

[FIX] DtoValueValidator on unwanted validation of Formula properties

---

.github/workflows/nuget-reference-check.yml
CDP4-SDK.sln
CDP4Common/CDP4Common.csproj
CDP4Dal/CDP4Dal.csproj
CDP4DalCommon/CDP4DalCommon.csproj
CDP4JsonFileDal.NetCore.Tests/CDP4JsonFileDal.NetCore.Tests.csproj
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4MessagePackSerializer/CDP4MessagePackSerializer.csproj
CDP4Reporting/CDP4Reporting.csproj
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4Rules/CDP4Rules.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4ServicesMessaging/CDP4ServicesMessaging.csproj
CDP4Web/CDP4Web.csproj
CDP4WspDal/CDP4WspDal.csproj

[Update] System.Text.RegularExpressions version 4.3.1 - resolves transitive vulnerability
[Add] GH action that fails when a vulnerability is found

[Update] System.Text.RegularExpressions version 4.3.1 - resolves transitive vulnerability

---

CDP4Common/CDP4Common.csproj
CDP4Dal/CDP4Dal.csproj
CDP4DalCommon/CDP4DalCommon.csproj
CDP4JsonFileDal/CDP4JsonFileDal.csproj
CDP4JsonSerializer/CDP4JsonSerializer.csproj
CDP4MessagePackSerializer/CDP4MessagePackSerializer.csproj
CDP4Reporting/CDP4Reporting.csproj
CDP4RequirementsVerification/CDP4RequirementsVerification.csproj
CDP4Rules/CDP4Rules.csproj
CDP4ServicesDal/CDP4ServicesDal.csproj
CDP4ServicesMessaging/CDP4ServicesMessaging.csproj
CDP4Web/CDP4Web.csproj

Version Bump
